version: 0.0.2
config:
    project:
        name: vrf-avs
        version: 0.1.0
        context: devnet
        project_uuid: "seanmcgary:vrf"
        telemetry_enabled: true
        templateBaseUrl: https://github.com/Layr-Labs/hourglass-avs-template
        templateVersion: v0.0.13
